### ISSUE TITLE
Column sorting with dates?

### ISSUE THREAD

**Issue by jsodeman** [matfish2/vue-tables#94]
Is it possible to sort date columns without the datepicker library?

I've tried adding the columns to dateColumns and setting a toMomentFormat but now I'm getting an error about datepicker being missing. I don't need to filter, just sort.

**Comment by matfish2** [comment]
I should probably remove the datepicker requirement when the column is not filterable (either because `filterByColumn` is set to `false`, or it is not included in the `filterable` array). 
Otherwise, it makes sense to require it, as a free text filter is not really the way to go.

In the meantime, just iterate over your data and turn the date strings into `moment` objects yourself before passing it to the component (which is exactly what `toMomentFormat` does behind the scenes).

**Comment by jsodeman** [comment]
Thanks! If anyone else needs this you don't need to set dateColumns for date sorting to work using moment objects.
